#!/usr/bin/env python

#import palette.hex  as hexp
#import palette.rgb  as rgbp
#import palette.util as util

import alice.palette as palette
import alice.util as util

from argparse import ArgumentParser

parser = ArgumentParser(
  prog="alice",
  description="query color info from the alice color scheme",
  epilog="Alice (https://github.com/wreedb/alice)"
)

parser.add_argument(
  "-s", "--scheme",
  help="scheme variant to use: [normal (default), bright]"
)
parser.add_argument(
  "-f", "--format",
  help="color format to use: [hex, rgb]",
  required=True
)

parser.add_argument(
  "-c","--color",
  help="output a single color: [black,red,green,yellow,blue,magenta,cyan,white]"
)

parser.add_argument(
  "-p", "--preview",
  help="show a preview of the color(s) in your terminal, NOTE: this only works for 'truecolor' terminals",
  action="store_true"
)

args = parser.parse_args()

builder = {
  "preview": False,
  "scheme": "",
  "format": ""
}

if args.preview:
  builder["preview"] = True

match args.scheme:
  case "normal":
    builder["scheme"] = "normal"
  case "bright":
    builder["scheme"] = "bright"
  case _:
    print("Invalid argument to -s/--scheme")
    print("Expeceted one of: normal,bright")
    exit(1)

match args.format:
  case "rgb":
    builder["format"] = "rgb"
  case "hex":
    builder["format"] = "hex"
  case _:
    print("invalid argument to -f/--format")
    print("expected one of: hex,rgb")
    exit(1)

if args.color:
  match args.color:
    case "black":
      color_index = 0
    case "red":
      color_index = 1
    case "green":
      color_index = 2
    case "yellow":
      color_index = 3
    case "blue":
      color_index = 4
    case "magenta":
      color_index = 5
    case "cyan":
      color_index = 6
    case "white":
      color_index = 7
    case _:
      print("invalid argument to -c/--color")
      print("expected one of:")
      print("black,red,green,yellow,blue,magenta,cyan,white")
      exit(1)

  match builder["scheme"]:

    case "normal":
      if builder["format"] == "rgb":
        out = util.get_rgb_color(palette.normal["rgb"], color_index, builder["preview"], palette.normal["rgb"][color_index])
        print(out)
      elif builder["format"] == "hex":
        out = util.get_hex_color(palette.normal["hex"], color_index, builder["preview"], palette.normal["rgb"][color_index])
        print(out)
      else:
        print("Internal error: (format = %s)\nPlease file an issue." % (builder["format"]))
        exit(1)

    case "bright":
      if builder["format"] == "rgb":
        out = util.get_rgb_color(palette.bright["rgb"], color_index, builder["preview"], palette.bright["rgb"][color_index])
        print(out)
      elif builder["format"] == "hex":
        out = util.get_hex_color(palette.bright["hex"], color_index, builder["preview"], palette.bright["rgb"][color_index])
        print(out)
      else:
        print("Internal error: (format = %s)\nPlease file an issue." % (builder["format"]))
        exit(1)

    case _:
      print("Internal error: (scheme = %s)\nPlease file an issue." % (builder["scheme"]))
      exit(1)

else:

  match builder["scheme"]:

    case "normal":
      if builder["format"] == "rgb":
        out = util.get_rgb_scheme(palette.normal["rgb"], builder["preview"], palette.normal["rgb"])
        print(out)
      elif builder["format"] == "hex":
        out = util.get_hex_scheme(palette.normal["hex"], builder["preview"], palette.normal["rgb"])
        print(out)
      else:
        print("Internal error: (format = %s)\nPlease file an issue." % (builder["format"]))
        exit(1)

    case "bright":
      if builder["format"] == "rgb":
        out = util.get_rgb_scheme(palette.bright["rgb"], builder["preview"], palette.bright["rgb"])
        print(out)
      elif builder["format"] == "hex":
        out = util.get_hex_scheme(palette.bright["hex"], builder["preview"], palette.bright["rgb"])
        print(out)
      else:
        print("Internal error: (format = %s)\nPlease file an issue." % (builder["format"]))
        exit(1)


    case _:
      print("Internal error: (scheme = %s)\nPlease file an issue." % (builder["scheme"]))
      exit(1)

